// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBuilding.Infrastructure.Data;

#nullable disable

namespace SmartBuilding.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SmartBuildingDbContext))]
    [Migration("20260929185556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("card_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_access_cards");

                    b.HasIndex("CardNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_access_cards_card_number");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_cards_user_id");

                    b.ToTable("access_cards", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_card_id");

                    b.Property<Guid>("AccessPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_point_id");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_access_events");

                    b.HasIndex("AccessCardId")
                        .HasDatabaseName("ix_access_events_access_card_id");

                    b.HasIndex("AccessPointId")
                        .HasDatabaseName("ix_access_events_access_point_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_access_events_occurred_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_events_user_id");

                    b.ToTable("access_events", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_point_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_access_permissions");

                    b.HasIndex("AccessPointId")
                        .HasDatabaseName("ix_access_permissions_access_point_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_permissions_user_id");

                    b.ToTable("access_permissions", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<bool>("SupportsEntry")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_entry");

                    b.Property<bool>("SupportsExit")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_exit");

                    b.HasKey("Id")
                        .HasName("pk_access_points");

                    b.HasIndex("FloorId")
                        .HasDatabaseName("ix_access_points_floor_id");

                    b.ToTable("access_points", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_buildings");

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_floors");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_floors_building_id");

                    b.ToTable("floors", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.OccupancySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<DateTime?>("ExitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exited_at");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_occupancy_sessions");

                    b.HasIndex("ExitedAt")
                        .HasDatabaseName("ix_occupancy_sessions_exited_at");

                    b.HasIndex("FloorId")
                        .HasDatabaseName("ix_occupancy_sessions_floor_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_occupancy_sessions_user_id");

                    b.ToTable("occupancy_sessions", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.SecurityAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_point_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_security_alerts");

                    b.HasIndex("AccessPointId")
                        .HasDatabaseName("ix_security_alerts_access_point_id");

                    b.ToTable("security_alerts", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessCard", b =>
                {
                    b.HasOne("SmartBuilding.Domain.Entities.User", "User")
                        .WithMany("AccessCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_cards_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessEvent", b =>
                {
                    b.HasOne("SmartBuilding.Domain.Entities.AccessCard", "AccessCard")
                        .WithMany("AccessEvents")
                        .HasForeignKey("AccessCardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_access_events_access_cards_access_card_id");

                    b.HasOne("SmartBuilding.Domain.Entities.AccessPoint", "AccessPoint")
                        .WithMany("AccessEvents")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_events_access_points_access_point_id");

                    b.HasOne("SmartBuilding.Domain.Entities.User", "User")
                        .WithMany("AccessEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_access_events_users_user_id");

                    b.Navigation("AccessCard");

                    b.Navigation("AccessPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessPermission", b =>
                {
                    b.HasOne("SmartBuilding.Domain.Entities.AccessPoint", "AccessPoint")
                        .WithMany("AccessPermissions")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_permissions_access_points_access_point_id");

                    b.HasOne("SmartBuilding.Domain.Entities.User", "User")
                        .WithMany("AccessPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_permissions_users_user_id");

                    b.Navigation("AccessPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessPoint", b =>
                {
                    b.HasOne("SmartBuilding.Domain.Entities.Floor", "Floor")
                        .WithMany("AccessPoints")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_points_floors_floor_id");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.Floor", b =>
                {
                    b.HasOne("SmartBuilding.Domain.Entities.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_floors_buildings_building_id");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.OccupancySession", b =>
                {
                    b.HasOne("SmartBuilding.Domain.Entities.Floor", "Floor")
                        .WithMany("OccupancySessions")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_occupancy_sessions_floors_floor_id");

                    b.HasOne("SmartBuilding.Domain.Entities.User", "User")
                        .WithMany("OccupancySessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_occupancy_sessions_users_user_id");

                    b.Navigation("Floor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.SecurityAlert", b =>
                {
                    b.HasOne("SmartBuilding.Domain.Entities.AccessPoint", "AccessPoint")
                        .WithMany("SecurityAlerts")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_security_alerts_access_points_access_point_id");

                    b.Navigation("AccessPoint");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessCard", b =>
                {
                    b.Navigation("AccessEvents");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.AccessPoint", b =>
                {
                    b.Navigation("AccessEvents");

                    b.Navigation("AccessPermissions");

                    b.Navigation("SecurityAlerts");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.Floor", b =>
                {
                    b.Navigation("AccessPoints");

                    b.Navigation("OccupancySessions");
                });

            modelBuilder.Entity("SmartBuilding.Domain.Entities.User", b =>
                {
                    b.Navigation("AccessCards");

                    b.Navigation("AccessEvents");

                    b.Navigation("AccessPermissions");

                    b.Navigation("OccupancySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
